# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@lastest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'frameworks/kcompletion': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/knewstuff': '@latest-kf6'
    'frameworks/kiconthemes': '@latest-kf6'
    'frameworks/ktexteditor': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/karchive': '@latest-kf6'
    'frameworks/kparts': '@latest-kf6'
    'frameworks/syntax-highlighting': '@latest-kf6'
    'frameworks/ktextwidgets': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'education/analitza': '@same'

Options:
  cmake-options: "-DENABLE_EMBEDDED_DOCUMENTATION=ON"
  require-passing-tests-on: ['Linux', 'Windows']
