# SPDX-FileCopyrightText: 2024, 2025 Scarlett Moore <sgmoore@kde.org>
#
# SPDX-License-Identifier: CC0-1.0
---
name: cantor
confinement: strict
grade: stable
base: core24
adopt-info: cantor
apps:
  cantor:
    extensions:
      - kde-neon-6
    common-id: org.kde.cantor.desktop
    desktop: usr/share/applications/org.kde.cantor.desktop
    command: usr/bin/cantor
environment:
  PATH_TO_CANTOR_PLUGINS: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins/cantor/backends
slots:
  session-dbus-interface:
    interface: dbus
    name: org.kde.cantor
    bus: session
parts:
  analitza:
    plugin: cmake
    build-packages:
      - cmake
      - libncurses-dev
      - libreadline-dev
      - libgl-dev
      - libeigen3-dev
    source: https://invent.kde.org/education/analitza.git
    source-branch: master
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_WITH_QT6=ON
      - -DBUILD_TESTING=OFF
  libqalculate:
    plugin: autotools
    source: https://github.com/Qalculate/libqalculate/releases/download/v5.5.0/libqalculate-5.5.0.tar.gz
    autotools-configure-parameters:
      - --prefix=/usr
    build-packages:
      - autotools-dev
      - intltool
      - libgmp-dev
      - libmpfr-dev
      - libcurl4-openssl-dev
      - libicu-dev
      - icu-devtools
      - libxml2-dev
    stage-packages:
      - libgmp10
      - libmpfr6
      - libcurl4t64
      - libicu74
      - libxml2
  libgpgmepp-qt6:
    build-packages:
      - libassuan-dev
      - libgpg-error-dev
      - rsync
    stage-packages:
      - libassuan0
      - libgpg-error0
    source: https://www.gnupg.org/ftp/gcrypt/gpgme/gpgme-1.23.2.tar.bz2
    source-checksum: sha256/9499e8b1f33cccb6815527a1bc16049d35a6198a6c5fae0185f2bd561bce5224
    plugin: autotools
    autotools-configure-parameters:
      - --disable-gpgsm-test
      - --enable-languages=cpp,qt6
      - --prefix=/usr
      - --enable-fixed-path=/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
    build-environment: &buildenvironment
      - LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:/snap/kf6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/usr
      - PKG_CONFIG_PATH: /snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig
    override-build: |
      craftctl default
      rsync -a --ignore-existing $CRAFT_PART_INSTALL/ /
  poppler:
    after:
      - libgpgmepp-qt6
    plugin: cmake
    source: https://poppler.freedesktop.org/poppler-24.06.0.tar.xz
    build-packages:
      - cmake
      - libfreetype6-dev
      - libfontconfig1-dev
      - libjpeg-dev
      - zlib1g-dev
      - libnss3-dev
      - liblcms2-dev
      - libcurl4-openssl-dev
      - libopenjp2-7-dev
      - libboost-dev
      - libgl1-mesa-dev
      - libtiff-dev
      - libpulse0
    stage-packages:
      - libasn1-8-heimdal
      - libbrotli1
      - libcurl4t64
      - libdouble-conversion3
      - libfontconfig1
      - libfreetype6
      - libgraphite2-3
      - libgssapi3-heimdal
      - libharfbuzz0b
      - libhcrypto5t64-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libicu74
      - libjbig0
      - libjpeg-turbo8
      - libkrb5-26-heimdal
      - liblcms2-2
      - libldap2
      - libnghttp2-14
      - libnspr4
      - libnss3
      - libpcre2-16-0
      - libpng16-16
      - libpsl5
      - libroken19-heimdal
      - librtmp1
      - libsasl2-2
      - libssh-4
      - libtiff6
      - libwebp7
      - libwind0-heimdal
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libmd4c0
      - libopenjpip7
      - libtiff6
      - libpulse0
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DENABLE_QT5=OFF
      - -DENABLE_QT6=ON
      - -DBUILD_TESTING=OFF
    override-build: |
      craftctl default
      rsync -a --ignore-existing $CRAFT_PART_INSTALL/ /
  cantor:
    after:
      - analitza
      - libqalculate
      - poppler
    parse-info:
      - usr/share/metainfo/org.kde.cantor.appdata.xml
    plugin: cmake
    source: .
    source-type: local
    build-packages:
      - libmarkdown2-dev
      - libglib2.0-dev
      - liblapack-dev
      - libluajit-5.1-dev
      - libspectre-dev
      - pkg-config
      - python3-dev
      - r-base-core
      - libxslt-dev
    stage-packages:
      - libmarkdown2
      - libglib2.0-0
      - liblapack3
      - libluajit-5.1-2
      - libspectre1
      - python3
      - r-base-core
      - libpython3.12
      - libncurses6
      - libreadline8
      - libgl1
      - libglx-dev
      - lua-any
      - texlive-binaries
      - texlive-latex-base
      - maxima
      - octave
      - scilab
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_WITH_QT6=ON
      - -DBUILD_TESTING=OFF
    build-environment:
      - PATH: /snap/kf6-core24-sdk/current/usr/bin:/snap/kde-qt6-core24-sdk/current/usr/bin${PATH:+:$PATH}
      - PKG_CONFIG_PATH: /snap/kde-qt6-core24-sdk/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/pkgconfig:/snap/kf6-core24-sdk/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
      - XDG_DATA_DIRS: $CRAFT_STAGE/usr/share:/snap/kf6-core24-sdk/current/usr/share:/snap/kde-qt6-core24-sdk/current/usr/share:/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
      - XDG_CONFIG_HOME: $CRAFT_STAGE/etc/xdg:/snap/kf6-core24-sdk/current/etc/xdg:/snap/kde-qt6-core24-sdk/current/etc/xdg:/etc/xdg${XDG_CONFIG_HOME:+:$XDG_CONFIG_HOME}
      - LD_LIBRARY_PATH: /snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:/snap/kde-qt6-core24-sdk/current/usr/lib:/snap/kf6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/kf6-core24-sdk/current/usr/lib:$CRAFT_STAGE/usr/lib:$CRAFT_STAGE/lib/:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
    prime:
      - -usr/lib/*/cmake/*
      - -usr/include/*
      - -usr/share/ECM/*
      - -usr/share/man/*
      - -usr/bin/X11
      - -usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET_BUILD_FOR/6.0.0
      - -usr/lib/aspell/*
      - -usr/share/lintian
      - -etc/ssl/certs/java/cacerts
      - -etc/perl/XML/SAX/ParserDetails.ini
      - -var/lib/texmf/ls-R-TEXLIVEDIST
      - -var/lib/texmf/tex/generic/config/language.dat
      - -var/lib/texmf/tex/generic/config/language.dat.lua
      - -var/lib/texmf/tex/generic/config/language.def
      - -var/lib/texmf/fmtutil.cnf-TEXLIVEDIST
      - -var/lib/texmf/updmap.cfg-TEXLIVEDIST
      - -var/lib/texmf/ls-R-TEXMFMAIN
      - -var/lib/texmf/fmtutil.cnf-DEBIAN
      - -var/lib/texmf/updmap.cfg-DEBIAN
  gpu-2404:
    after: [cantor]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
        craftctl default
        ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
  cleanup:
    after:
      - cantor
    plugin: nil
    build-snaps:
      - core24
      - kf6-core24
    override-prime: |
        set -eux
        for snap in "core24" "kf6-core24"; do
            cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
        done


