/*
    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA  02110-1301, USA.

    ---
    Copyright (C) 2009 Alexander Rieder <alexanderrieder@gmail.com>
 */

#include "maximakeywords.h"

#include <QDebug>

MaximaKeywords::MaximaKeywords()
{

}


MaximaKeywords::~MaximaKeywords()
{

}

MaximaKeywords* MaximaKeywords::instance()
{
    static MaximaKeywords* inst=0;
    if(inst==0)
    {
        inst=new MaximaKeywords();
        inst->loadKeywords();
    }

    return inst;
}

void MaximaKeywords::loadKeywords()
{
    // Begin m_variables initialization - maximum 100 lines for each initialization insctruction
    m_variables << QLatin1String("_") << QLatin1String("__") << QLatin1String("%") << QLatin1String("%%")
                << QLatin1String("absboxchar") << QLatin1String("activecontexts") << QLatin1String("additive")
                << QLatin1String("algebraic") << QLatin1String("algepsilon") << QLatin1String("algexact")
                << QLatin1String("aliases") << QLatin1String("all_dotsimp_denoms") << QLatin1String("allbut")
                << QLatin1String("allsym") << QLatin1String("arrays") << QLatin1String("askexp") << QLatin1String("assume_pos")
                << QLatin1String("assume_pos_pred") << QLatin1String("assumescalar") << QLatin1String("atomgrad")
                << QLatin1String("backsubst") << QLatin1String("berlefact") << QLatin1String("besselexpand")
                << QLatin1String("bftorat") << QLatin1String("bftrunc") << QLatin1String("boxchar") << QLatin1String("breakup")
                << QLatin1String("cauchysum") << QLatin1String("cflength") << QLatin1String("cframe_flag")
                << QLatin1String("cnonmet_flag") << QLatin1String("context") << QLatin1String("contexts")
                << QLatin1String("cosnpiflag") << QLatin1String("ctaypov") << QLatin1String("ctaypt")
                << QLatin1String("ctayswitch") << QLatin1String("ctayvar") << QLatin1String("ct_coords")
                << QLatin1String("ctorsion_flag") << QLatin1String("ctrgsimp") << QLatin1String("current_let_rule_package")
                << QLatin1String("debugmode") << QLatin1String("default_let_rule_package") << QLatin1String("demoivre")
                << QLatin1String("dependencies") << QLatin1String("derivabbrev") << QLatin1String("derivsubst")
                << QLatin1String("detout") << QLatin1String("diagmetric") << QLatin1String("dim") << QLatin1String("dispflag")
                << QLatin1String("display2d") << QLatin1String("display_format_internal") << QLatin1String("doallmxops")
                << QLatin1String("domain") << QLatin1String("domxexpt") << QLatin1String("domxmxops")
                << QLatin1String("domxnctimes") << QLatin1String("dontfactor") << QLatin1String("doscmxops")
                << QLatin1String("doscmxplus") << QLatin1String("dot0nscsimp") << QLatin1String("dot0simp")
                << QLatin1String("dot1simp") << QLatin1String("dotassoc") << QLatin1String("dotconstrules")
                << QLatin1String("dotdistrib") << QLatin1String("dotexptsimp") << QLatin1String("dotident")
                << QLatin1String("dotscrules") << QLatin1String("draw_graph_program") << QLatin1String("%edispflag")
                << QLatin1String("%emode") << QLatin1String("%enumer") << QLatin1String("epsilon_lp")
                << QLatin1String("erfflag") << QLatin1String("error") << QLatin1String("error_size")
                << QLatin1String("error_syms") << QLatin1String("%e_to_numlog") << QLatin1String("evflag")
                << QLatin1String("evfun") << QLatin1String("expandwrt_denom") << QLatin1String("expon")
                << QLatin1String("exponentialize") << QLatin1String("expop") << QLatin1String("exptdispflag")
                << QLatin1String("exptisolate") << QLatin1String("exptsubst") << QLatin1String("facexpand")
                << QLatin1String("factlim") << QLatin1String("factorflag") << QLatin1String("file_output_append")
                << QLatin1String("file_search_demo") << QLatin1String("file_search_lisp") << QLatin1String("file_search_maxima")
                << QLatin1String("find_root_abs") << QLatin1String("find_root_error") << QLatin1String("find_root_rel")
                << QLatin1String("flipflag") << QLatin1String("float2bf") << QLatin1String("fortindent")
                << QLatin1String("fortspaces") << QLatin1String("fpprec") << QLatin1String("fpprintprec")
                << QLatin1String("functions") << QLatin1String("gammalim") << QLatin1String("gdet") << QLatin1String("genindex")
                << QLatin1String("gensumnum") << QLatin1String("GGFCFMAX") << QLatin1String("GGFINFINITY")
                << QLatin1String("globalsolve") << QLatin1String("gradefs") << QLatin1String("grind")
                << QLatin1String("halfangles") << QLatin1String("%iargs") << QLatin1String("ibase") << QLatin1String("icounter")
                << QLatin1String("idummyx") << QLatin1String("ieqnprint") << QLatin1String("iframe_bracket_form")
                << QLatin1String("igeowedge_flag") << QLatin1String("imetric") << QLatin1String("inchar")
                << QLatin1String("infeval") << QLatin1String("inflag") << QLatin1String("infolists")
                << QLatin1String("in_netmath") << QLatin1String("integrate_use_rootsof")
                << QLatin1String("integration_constant") << QLatin1String("integration_constant_counter")
                << QLatin1String("intfaclim") << QLatin1String("isolate_wrt_times") << QLatin1String("keepfloat")
                << QLatin1String("labels") << QLatin1String("letrat") << QLatin1String("let_rule_packages")
                << QLatin1String("lhospitallim") << QLatin1String("limsubst") << QLatin1String("linechar")
                << QLatin1String("linel") << QLatin1String("linenum") << QLatin1String("linsolve_params")
                << QLatin1String("linsolvewarn") << QLatin1String("lispdisp") << QLatin1String("listarith")
                << QLatin1String("listconstvars") << QLatin1String("listdummyvars") << QLatin1String("lmxchar")
                << QLatin1String("loadprint") << QLatin1String("logabs") << QLatin1String("logarc")
                << QLatin1String("logconcoeffp") << QLatin1String("logexpand") << QLatin1String("lognegint")
                << QLatin1String("lognumer") << QLatin1String("logsimp") << QLatin1String("m1pbranch")
                << QLatin1String("macroexpansion") << QLatin1String("maperror") << QLatin1String("mapprint")
                << QLatin1String("matrix_element_add") << QLatin1String("matrix_element_mult")
                << QLatin1String("matrix_element_transpose") << QLatin1String("maxapplydepth")
                << QLatin1String("maxapplyheight") << QLatin1String("maxima_tempdir") << QLatin1String("maxima_userdir")
                << QLatin1String("maxnegex") << QLatin1String("maxposex") << QLatin1String("maxpsifracdenom")
                << QLatin1String("maxpsifracnum") << QLatin1String("maxpsinegint") << QLatin1String("maxpsiposint")
                << QLatin1String("maxtayorder") << QLatin1String("method") << QLatin1String("mode_check_errorp")
                << QLatin1String("mode_checkp") << QLatin1String("mode_check_warnp") << QLatin1String("modulus")
                << QLatin1String("multiplicities") << QLatin1String("myoptions") << QLatin1String("negdistrib")
                << QLatin1String("negsumdispflag") << QLatin1String("newtonepsilon") << QLatin1String("newtonmaxiter")
                << QLatin1String("niceindicespref") << QLatin1String("nolabels") << QLatin1String("nonegative_lp")
                << QLatin1String("noundisp") << QLatin1String("obase") << QLatin1String("opproperties")
                << QLatin1String("opsubst") << QLatin1String("optimprefix") << QLatin1String("optionset")
                << QLatin1String("outchar") << QLatin1String("packagefile") << QLatin1String("partswitch")
                << QLatin1String("pfeformat") << QLatin1String("%piargs") << QLatin1String("piece")
                << QLatin1String("plot_options") << QLatin1String("poislim") << QLatin1String("poly_coefficient_ring")
                << QLatin1String("poly_elimination_order") << QLatin1String("poly_grobner_algorithm")
                << QLatin1String("poly_grobner_debug") << QLatin1String("poly_monomial_order")
                << QLatin1String("poly_primary_elimination_order") << QLatin1String("poly_return_term_list")
                << QLatin1String("poly_secondary_elimination_order") << QLatin1String("poly_top_reduction_only")
                << QLatin1String("powerdisp") << QLatin1String("prederror") << QLatin1String("primep_number_of_tests")
                << QLatin1String("product_use_gamma") << QLatin1String("programmode") << QLatin1String("prompt")
                << QLatin1String("psexpand") << QLatin1String("radexpand") << QLatin1String("radsubstflag")
                << QLatin1String("random_beta_algorithm") << QLatin1String("random_binomial_algorithm")
                << QLatin1String("random_chi2_algorithm") << QLatin1String("random_exp_algorithm")
                << QLatin1String("random_f_algorithm") << QLatin1String("random_gamma_algorithm")
                << QLatin1String("random_geometric_algorithm") << QLatin1String("random_hypergeometric_algorithm")
                << QLatin1String("random_negative_binomial_algorithm") << QLatin1String("random_normal_algorithm")
                << QLatin1String("random_poisson_algorithm") << QLatin1String("random_student_t_algorithm")
                << QLatin1String("ratalgdenom") << QLatin1String("ratchristof") << QLatin1String("ratdenomdivide")
                << QLatin1String("rateinstein") << QLatin1String("ratepsilon") << QLatin1String("ratexpand")
                << QLatin1String("ratfac") << QLatin1String("ratmx") << QLatin1String("ratprint") << QLatin1String("ratriemann")
                << QLatin1String("ratsimpexpons") << QLatin1String("ratvars") << QLatin1String("ratweights")
                << QLatin1String("ratweyl") << QLatin1String("ratwtlvl") << QLatin1String("realonly")
                << QLatin1String("refcheck") << QLatin1String("rmxchar") << QLatin1String("%rnum_list")
                << QLatin1String("rombergabs") << QLatin1String("rombergit") << QLatin1String("rombergmin")
                << QLatin1String("rombergtol") << QLatin1String("rootsconmode") << QLatin1String("rootsepsilon")
                << QLatin1String("savedef") << QLatin1String("savefactors") << QLatin1String("scalarmatrixp")
                << QLatin1String("setcheck") << QLatin1String("setcheckbreak") << QLatin1String("setval")
                << QLatin1String("showtime") << QLatin1String("simplify_products") << QLatin1String("simpsum")
                << QLatin1String("sinnpiflag") << QLatin1String("solvedecomposes") << QLatin1String("solveexplicit")
                << QLatin1String("solvefactors") << QLatin1String("solve_inconsistent_error") << QLatin1String("solvenullwarn")
                << QLatin1String("solveradcan") << QLatin1String("solvetrigwarn") << QLatin1String("sparse")
                << QLatin1String("sqrtdispflag") << QLatin1String("stardisp") << QLatin1String("stats_numer")
                << QLatin1String("stringdisp") << QLatin1String("sublis_apply_lambda") << QLatin1String("sumexpand")
                << QLatin1String("sumsplitfact") << QLatin1String("taylordepth") << QLatin1String("taylor_logexpand")
                << QLatin1String("taylor_order_coefficients") << QLatin1String("taylor_truncate_polynomials")
                << QLatin1String("tensorkill") << QLatin1String("testsuite_files") << QLatin1String("timer_devalue")
                << QLatin1String("tlimswitch") << QLatin1String("transcompile") << QLatin1String("transrun");

    m_variables << QLatin1String("tr_array_as_ref") << QLatin1String("tr_bound_function_applyp")
                << QLatin1String("tr_file_tty_messagesp") << QLatin1String("tr_float_can_branch_complex")
                << QLatin1String("tr_function_call_default") << QLatin1String("trigexpandplus")
                << QLatin1String("trigexpandtimes") << QLatin1String("triginverses") << QLatin1String("trigsign")
                << QLatin1String("tr_numer") << QLatin1String("tr_optimize_max_loop") << QLatin1String("tr_semicompile")
                << QLatin1String("tr_state_vars") << QLatin1String("tr_warn_bad_function_calls")
                << QLatin1String("tr_warn_fexpr") << QLatin1String("tr_warn_meval") << QLatin1String("tr_warn_mode")
                << QLatin1String("tr_warn_undeclared") << QLatin1String("tr_warn_undefined_variable")
                << QLatin1String("tr_windy") << QLatin1String("ttyoff") << QLatin1String("use_fast_arrays")
                << QLatin1String("values") << QLatin1String("vect_cross") << QLatin1String("verbose")
                << QLatin1String("zerobern") << QLatin1String("zeta%pi");
    //Finish m_variables initialization

    // Begin m_functions initialization - maximum 100 lines for each initialization insctruction
    m_functions << QLatin1String("abasep") << QLatin1String("abs") << QLatin1String("absint")
                << QLatin1String("absolute_real_time") << QLatin1String("acos") << QLatin1String("acosh")
                << QLatin1String("acot") << QLatin1String("acoth") << QLatin1String("acsc") << QLatin1String("acsch")
                << QLatin1String("activate") << QLatin1String("addcol") << QLatin1String("add_edge")
                << QLatin1String("add_edges") << QLatin1String("addmatrices") << QLatin1String("addrow")
                << QLatin1String("add_vertex") << QLatin1String("add_vertices") << QLatin1String("adjacency_matrix")
                << QLatin1String("adjoin") << QLatin1String("adjoint") << QLatin1String("af") << QLatin1String("agd")
                << QLatin1String("airy_ai") << QLatin1String("airy_bi") << QLatin1String("airy_dai")
                << QLatin1String("airy_dbi") << QLatin1String("algsys") << QLatin1String("alg_type") << QLatin1String("alias")
                << QLatin1String("allroots") << QLatin1String("alphacharp") << QLatin1String("alphanumericp")
                << QLatin1String("antid") << QLatin1String("antidiff") << QLatin1String("AntiDifference")
                << QLatin1String("append") << QLatin1String("appendfile") << QLatin1String("apply") << QLatin1String("apply1")
                << QLatin1String("apply2") << QLatin1String("applyb1") << QLatin1String("apropos") << QLatin1String("args")
                << QLatin1String("arithmetic") << QLatin1String("arithsum") << QLatin1String("array")
                << QLatin1String("arrayapply") << QLatin1String("arrayinfo") << QLatin1String("arraymake")
                << QLatin1String("ascii") << QLatin1String("asec") << QLatin1String("asech") << QLatin1String("asin")
                << QLatin1String("asinh") << QLatin1String("askinteger") << QLatin1String("asksign") << QLatin1String("assoc")
                << QLatin1String("assoc_legendre_p") << QLatin1String("assoc_legendre_q") << QLatin1String("assume")
                << QLatin1String("asympa") << QLatin1String("at") << QLatin1String("atan") << QLatin1String("atan2")
                << QLatin1String("atanh") << QLatin1String("atensimp") << QLatin1String("atom") << QLatin1String("atvalue")
                << QLatin1String("augcoefmatrix") << QLatin1String("augmented_lagrangian_method") << QLatin1String("av")
                << QLatin1String("average_degree") << QLatin1String("backtrace") << QLatin1String("barsplot")
                << QLatin1String("bashindices") << QLatin1String("batch") << QLatin1String("batchload") << QLatin1String("bc2")
                << QLatin1String("bdvac") << QLatin1String("belln") << QLatin1String("bern") << QLatin1String("bernpoly")
                << QLatin1String("bessel") << QLatin1String("bessel_i") << QLatin1String("bessel_j")
                << QLatin1String("bessel_k") << QLatin1String("bessel_y") << QLatin1String("beta") << QLatin1String("bezout")
                << QLatin1String("bffac") << QLatin1String("bfhzeta") << QLatin1String("bfloat") << QLatin1String("bfloatp")
                << QLatin1String("bfpsi") << QLatin1String("bfpsi0") << QLatin1String("bfzeta")
                << QLatin1String("biconected_components") << QLatin1String("bimetric") << QLatin1String("binomial")
                << QLatin1String("bipartition") << QLatin1String("block") << QLatin1String("blockmatrixp")
                << QLatin1String("bode_gain") << QLatin1String("bode_phase") << QLatin1String("bothcoef")
                << QLatin1String("box") << QLatin1String("boxplot") << QLatin1String("break") << QLatin1String("bug_report")
                << QLatin1String("build_info") << QLatin1String("buildq") << QLatin1String("burn") << QLatin1String("cabs")
                << QLatin1String("canform") << QLatin1String("canten") << QLatin1String("cardinality") << QLatin1String("carg")
                << QLatin1String("cartan") << QLatin1String("cartesian_product") << QLatin1String("catch")
                << QLatin1String("cbffac") << QLatin1String("cdf_bernoulli") << QLatin1String("cdf_beta")
                << QLatin1String("cdf_binomial") << QLatin1String("cdf_cauchy") << QLatin1String("cdf_chi2")
                << QLatin1String("cdf_continuous_uniform") << QLatin1String("cdf_discrete_uniform") << QLatin1String("cdf_exp")
                << QLatin1String("cdf_f") << QLatin1String("cdf_gamma") << QLatin1String("cdf_geometric")
                << QLatin1String("cdf_gumbel") << QLatin1String("cdf_hypergeometric") << QLatin1String("cdf_laplace")
                << QLatin1String("cdf_logistic") << QLatin1String("cdf_lognormal") << QLatin1String("cdf_negative_binomial")
                << QLatin1String("cdf_normal") << QLatin1String("cdf_pareto") << QLatin1String("cdf_poisson")
                << QLatin1String("cdf_rank_sum") << QLatin1String("cdf_rayleigh") << QLatin1String("cdf_signed_rank")
                << QLatin1String("cdf_student_t") << QLatin1String("cdf_weibull") << QLatin1String("cdisplay")
                << QLatin1String("ceiling") << QLatin1String("central_moment") << QLatin1String("cequal")
                << QLatin1String("cequalignore") << QLatin1String("cf") << QLatin1String("cfdisrep")
                << QLatin1String("cfexpand") << QLatin1String("cgeodesic") << QLatin1String("cgreaterp")
                << QLatin1String("cgreaterpignore") << QLatin1String("changename") << QLatin1String("changevar")
                << QLatin1String("chaosgame") << QLatin1String("charat") << QLatin1String("charfun")
                << QLatin1String("charfun2") << QLatin1String("charlist") << QLatin1String("charp")
                << QLatin1String("charpoly") << QLatin1String("chebyshev_t") << QLatin1String("chebyshev_u")
                << QLatin1String("checkdiv") << QLatin1String("check_overlaps") << QLatin1String("cholesky")
                << QLatin1String("christof") << QLatin1String("chromatic_index") << QLatin1String("chromatic_number")
                << QLatin1String("cint") << QLatin1String("circulant_graph") << QLatin1String("clear_edge_weight")
                << QLatin1String("clear_rules") << QLatin1String("clear_vertex_label") << QLatin1String("clebsch_graph")
                << QLatin1String("clessp") << QLatin1String("clesspignore") << QLatin1String("close")
                << QLatin1String("closefile") << QLatin1String("cmetric") << QLatin1String("coeff")
                << QLatin1String("coefmatrix") << QLatin1String("cograd") << QLatin1String("col") << QLatin1String("collapse")
                << QLatin1String("collectterms") << QLatin1String("columnop") << QLatin1String("columnspace")
                << QLatin1String("columnswap") << QLatin1String("columnvector") << QLatin1String("combination")
                << QLatin1String("combine") << QLatin1String("comp2pui") << QLatin1String("compare")
                << QLatin1String("compfile") << QLatin1String("compile") << QLatin1String("compile_file")
                << QLatin1String("complement_graph") << QLatin1String("complete_bipartite_graph")
                << QLatin1String("complete_graph") << QLatin1String("components") << QLatin1String("concan")
                << QLatin1String("concat") << QLatin1String("conjugate") << QLatin1String("conmetderiv")
                << QLatin1String("connected_components") << QLatin1String("connect_vertices") << QLatin1String("cons")
                << QLatin1String("constantp") << QLatin1String("constituent") << QLatin1String("cont2part")
                << QLatin1String("content") << QLatin1String("continuous_freq") << QLatin1String("contortion")
                << QLatin1String("contour_plot") << QLatin1String("contract") << QLatin1String("contract_edge")
                << QLatin1String("contragrad") << QLatin1String("contrib_ode") << QLatin1String("convert")
                << QLatin1String("coord") << QLatin1String("copy") << QLatin1String("copy_graph") << QLatin1String("copylist")
                << QLatin1String("copymatrix") << QLatin1String("cor") << QLatin1String("cos") << QLatin1String("cosh")
                << QLatin1String("cot") << QLatin1String("coth") << QLatin1String("cov") << QLatin1String("cov1")
                << QLatin1String("covdiff") << QLatin1String("covect") << QLatin1String("covers")
                << QLatin1String("create_graph") << QLatin1String("create_list") << QLatin1String("csc")
                << QLatin1String("csch") << QLatin1String("csetup") << QLatin1String("cspline") << QLatin1String("ctaylor")
                << QLatin1String("ct_coordsys") << QLatin1String("ctransform") << QLatin1String("ctranspose")
                << QLatin1String("cube_graph") << QLatin1String("cunlisp") << QLatin1String("cv")
                << QLatin1String("cycle_digraph") << QLatin1String("cycle_graph") << QLatin1String("dblint")
                << QLatin1String("deactivate") << QLatin1String("declare") << QLatin1String("declare_translated")
                << QLatin1String("declare_weight") << QLatin1String("decsym") << QLatin1String("defcon")
                << QLatin1String("define") << QLatin1String("define_variable") << QLatin1String("defint")
                << QLatin1String("defmatch") << QLatin1String("defrule") << QLatin1String("deftaylor")
                << QLatin1String("degree_sequence") << QLatin1String("del") << QLatin1String("delete")
                << QLatin1String("deleten") << QLatin1String("delta") << QLatin1String("demo") << QLatin1String("demoivre")
                << QLatin1String("denom") << QLatin1String("depends") << QLatin1String("derivdegree")
                << QLatin1String("derivlist") << QLatin1String("describe") << QLatin1String("desolve")
                << QLatin1String("determinant") << QLatin1String("dgauss_a") << QLatin1String("dgauss_b")
                << QLatin1String("dgeev") << QLatin1String("dgesvd") << QLatin1String("diag") << QLatin1String("diagmatrix")
                << QLatin1String("diag_matrix") << QLatin1String("diagmatrixp") << QLatin1String("diameter")
                << QLatin1String("diff") << QLatin1String("digitcharp") << QLatin1String("dimacs_export")
                << QLatin1String("dimacs_import") << QLatin1String("dimension") << QLatin1String("direct")
                << QLatin1String("discrete_freq") << QLatin1String("disjoin") << QLatin1String("disjointp")
                << QLatin1String("disolate") << QLatin1String("disp") << QLatin1String("dispcon") << QLatin1String("dispform")
                << QLatin1String("dispfun") << QLatin1String("dispJordan") << QLatin1String("display")
                << QLatin1String("disprule") << QLatin1String("dispterms") << QLatin1String("distrib")
                << QLatin1String("divide") << QLatin1String("divisors") << QLatin1String("divsum") << QLatin1String("dkummer_m")
                << QLatin1String("dkummer_u") << QLatin1String("dlange") << QLatin1String("dodecahedron_graph")
                << QLatin1String("dotproduct") << QLatin1String("dotsimp") << QLatin1String("dpart") << QLatin1String("draw")
                << QLatin1String("draw2d") << QLatin1String("draw3d") << QLatin1String("draw_graph") << QLatin1String("dscalar")
                << QLatin1String("echelon") << QLatin1String("edge_coloring") << QLatin1String("edges");

    m_functions << QLatin1String("eigens_by_jacobi") << QLatin1String("eigenvalues") << QLatin1String("eigenvectors")
                << QLatin1String("eighth") << QLatin1String("einstein") << QLatin1String("eivals") << QLatin1String("eivects")
                << QLatin1String("elapsed_real_time") << QLatin1String("elapsed_run_time") << QLatin1String("ele2comp")
                << QLatin1String("ele2polynome") << QLatin1String("ele2pui") << QLatin1String("elem")
                << QLatin1String("elementp") << QLatin1String("eliminate") << QLatin1String("elliptic_e")
                << QLatin1String("elliptic_ec") << QLatin1String("elliptic_eu") << QLatin1String("elliptic_f")
                << QLatin1String("elliptic_kc") << QLatin1String("elliptic_pi") << QLatin1String("ematrix")
                << QLatin1String("empty_graph") << QLatin1String("emptyp") << QLatin1String("endcons")
                << QLatin1String("entermatrix") << QLatin1String("entertensor") << QLatin1String("entier")
                << QLatin1String("equal") << QLatin1String("equalp") << QLatin1String("equiv_classes") << QLatin1String("erf")
                << QLatin1String("errcatch") << QLatin1String("error") << QLatin1String("errormsg") << QLatin1String("euler")
                << QLatin1String("ev") << QLatin1String("eval_string") << QLatin1String("evenp") << QLatin1String("every")
                << QLatin1String("evolution") << QLatin1String("evolution2d") << QLatin1String("evundiff")
                << QLatin1String("example") << QLatin1String("exp") << QLatin1String("expand") << QLatin1String("expandwrt")
                << QLatin1String("expandwrt_factored") << QLatin1String("explose") << QLatin1String("exponentialize")
                << QLatin1String("express") << QLatin1String("expt") << QLatin1String("exsec") << QLatin1String("extdiff")
                << QLatin1String("extract_linear_equations") << QLatin1String("extremal_subset") << QLatin1String("ezgcd")
                << QLatin1String("f90") << QLatin1String("facsum") << QLatin1String("factcomb") << QLatin1String("factor")
                << QLatin1String("factorfacsum") << QLatin1String("factorial") << QLatin1String("factorout")
                << QLatin1String("factorsum") << QLatin1String("facts") << QLatin1String("fast_central_elements")
                << QLatin1String("fast_linsolve") << QLatin1String("fasttimes") << QLatin1String("featurep")
                << QLatin1String("fft") << QLatin1String("fib") << QLatin1String("fibtophi") << QLatin1String("fifth")
                << QLatin1String("filename_merge") << QLatin1String("file_search") << QLatin1String("file_type")
                << QLatin1String("fillarray") << QLatin1String("findde") << QLatin1String("find_root") << QLatin1String("first")
                << QLatin1String("fix") << QLatin1String("flatten") << QLatin1String("flength") << QLatin1String("float")
                << QLatin1String("floatnump") << QLatin1String("floor") << QLatin1String("flower_snark")
                << QLatin1String("flush") << QLatin1String("flush1deriv") << QLatin1String("flushd") << QLatin1String("flushnd")
                << QLatin1String("forget") << QLatin1String("fortran") << QLatin1String("fourcos")
                << QLatin1String("fourexpand") << QLatin1String("fourier") << QLatin1String("fourint")
                << QLatin1String("fourintcos") << QLatin1String("fourintsin") << QLatin1String("foursimp")
                << QLatin1String("foursin") << QLatin1String("fourth") << QLatin1String("fposition")
                << QLatin1String("frame_bracket") << QLatin1String("freeof") << QLatin1String("freshline")
                << QLatin1String("from_adjacency_matrix") << QLatin1String("frucht_graph") << QLatin1String("full_listify")
                << QLatin1String("fullmap") << QLatin1String("fullmapl") << QLatin1String("fullratsimp")
                << QLatin1String("fullratsubst") << QLatin1String("fullsetify") << QLatin1String("funcsolve")
                << QLatin1String("fundef") << QLatin1String("funmake") << QLatin1String("funp") << QLatin1String("gamma")
                << QLatin1String("gauss_a") << QLatin1String("gauss_b") << QLatin1String("gaussprob") << QLatin1String("gcd")
                << QLatin1String("gcdex") << QLatin1String("gcdivide") << QLatin1String("gcfac") << QLatin1String("gcfactor")
                << QLatin1String("gd") << QLatin1String("genfact") << QLatin1String("gen_laguerre")
                << QLatin1String("genmatrix") << QLatin1String("geometric") << QLatin1String("geometric_mean")
                << QLatin1String("geosum") << QLatin1String("get") << QLatin1String("get_edge_weight")
                << QLatin1String("get_lu_factors") << QLatin1String("get_pixel") << QLatin1String("get_vertex_label")
                << QLatin1String("gfactor") << QLatin1String("gfactorsum") << QLatin1String("ggf") << QLatin1String("girth")
                << QLatin1String("global_variances") << QLatin1String("gnuplot_close") << QLatin1String("gnuplot_replot")
                << QLatin1String("gnuplot_reset") << QLatin1String("gnuplot_restart") << QLatin1String("gnuplot_start")
                << QLatin1String("go") << QLatin1String("Gosper") << QLatin1String("GosperSum") << QLatin1String("gradef")
                << QLatin1String("gramschmidt") << QLatin1String("graph6_decode") << QLatin1String("graph6_encode")
                << QLatin1String("graph6_export") << QLatin1String("graph6_import") << QLatin1String("graph_center")
                << QLatin1String("graph_charpoly") << QLatin1String("graph_eigenvalues") << QLatin1String("graph_order")
                << QLatin1String("graph_periphery") << QLatin1String("graph_product") << QLatin1String("graph_size")
                << QLatin1String("graph_union") << QLatin1String("grid_graph") << QLatin1String("grind")
                << QLatin1String("grobner_basis") << QLatin1String("grotzch_graph") << QLatin1String("hamilton_cycle")
                << QLatin1String("hamilton_path") << QLatin1String("hankel") << QLatin1String("harmonic")
                << QLatin1String("harmonic_mean") << QLatin1String("hav") << QLatin1String("heawood_graph")
                << QLatin1String("hermite") << QLatin1String("hessian") << QLatin1String("hilbert_matrix")
                << QLatin1String("hipow") << QLatin1String("histogram") << QLatin1String("hodge") << QLatin1String("horner")
                << QLatin1String("ic1") << QLatin1String("ic2") << QLatin1String("ic_convert") << QLatin1String("ichr1")
                << QLatin1String("ichr2") << QLatin1String("icosahedron_graph") << QLatin1String("icurvature")
                << QLatin1String("ident") << QLatin1String("identfor") << QLatin1String("identity") << QLatin1String("idiff")
                << QLatin1String("idim") << QLatin1String("idummy") << QLatin1String("ieqn") << QLatin1String("ifactors")
                << QLatin1String("iframes") << QLatin1String("ifs") << QLatin1String("ift") << QLatin1String("igeodesic_coords")
                << QLatin1String("ilt") << QLatin1String("imagpart") << QLatin1String("imetric")
                << QLatin1String("implicit_derivative") << QLatin1String("implicit_plot") << QLatin1String("indexed_tensor")
                << QLatin1String("indices") << QLatin1String("induced_subgraph") << QLatin1String("inferencep")
                << QLatin1String("inference_result") << QLatin1String("infix") << QLatin1String("init_atensor")
                << QLatin1String("init_ctensor") << QLatin1String("in_neighbors") << QLatin1String("innerproduct")
                << QLatin1String("inpart") << QLatin1String("inprod") << QLatin1String("inrt") << QLatin1String("integerp")
                << QLatin1String("integer_partitions") << QLatin1String("integrate") << QLatin1String("intersect")
                << QLatin1String("intersection") << QLatin1String("intervalp") << QLatin1String("intopois")
                << QLatin1String("intosum") << QLatin1String("invariant1") << QLatin1String("invariant2")
                << QLatin1String("inverse_jacobi_cd") << QLatin1String("inverse_jacobi_cn")
                << QLatin1String("inverse_jacobi_cs") << QLatin1String("inverse_jacobi_dc")
                << QLatin1String("inverse_jacobi_dn") << QLatin1String("inverse_jacobi_ds")
                << QLatin1String("inverse_jacobi_nc") << QLatin1String("inverse_jacobi_nd")
                << QLatin1String("inverse_jacobi_ns") << QLatin1String("inverse_jacobi_sc")
                << QLatin1String("inverse_jacobi_sd") << QLatin1String("inverse_jacobi_sn") << QLatin1String("invert")
                << QLatin1String("invert_by_lu") << QLatin1String("inv_mod") << QLatin1String("is")
                << QLatin1String("is_biconnected") << QLatin1String("is_bipartite") << QLatin1String("is_connected")
                << QLatin1String("is_digraph") << QLatin1String("is_edge_in_graph") << QLatin1String("is_graph")
                << QLatin1String("is_graph_or_digraph") << QLatin1String("ishow") << QLatin1String("is_isomorphic")
                << QLatin1String("isolate") << QLatin1String("isomorphism") << QLatin1String("is_planar")
                << QLatin1String("isqrt") << QLatin1String("is_sconnected") << QLatin1String("is_tree")
                << QLatin1String("is_vertex_in_graph") << QLatin1String("items_inference") << QLatin1String("jacobi")
                << QLatin1String("jacobian") << QLatin1String("jacobi_cd") << QLatin1String("jacobi_cn")
                << QLatin1String("jacobi_cs") << QLatin1String("jacobi_dc") << QLatin1String("jacobi_dn")
                << QLatin1String("jacobi_ds") << QLatin1String("jacobi_nc") << QLatin1String("jacobi_nd")
                << QLatin1String("jacobi_ns") << QLatin1String("jacobi_p") << QLatin1String("jacobi_sc")
                << QLatin1String("jacobi_sd") << QLatin1String("jacobi_sn") << QLatin1String("JF") << QLatin1String("join")
                << QLatin1String("jordan") << QLatin1String("julia") << QLatin1String("kdels") << QLatin1String("kdelta")
                << QLatin1String("kill") << QLatin1String("killcontext") << QLatin1String("kostka")
                << QLatin1String("kron_delta") << QLatin1String("kronecker_product") << QLatin1String("kummer_m")
                << QLatin1String("kummer_u") << QLatin1String("kurtosis") << QLatin1String("kurtosis_bernoulli")
                << QLatin1String("kurtosis_beta") << QLatin1String("kurtosis_binomial") << QLatin1String("kurtosis_chi2")
                << QLatin1String("kurtosis_continuous_uniform") << QLatin1String("kurtosis_discrete_uniform")
                << QLatin1String("kurtosis_exp") << QLatin1String("kurtosis_f") << QLatin1String("kurtosis_gamma")
                << QLatin1String("kurtosis_geometric") << QLatin1String("kurtosis_gumbel")
                << QLatin1String("kurtosis_hypergeometric") << QLatin1String("kurtosis_laplace")
                << QLatin1String("kurtosis_logistic") << QLatin1String("kurtosis_lognormal")
                << QLatin1String("kurtosis_negative_binomial") << QLatin1String("kurtosis_normal")
                << QLatin1String("kurtosis_pareto") << QLatin1String("kurtosis_poisson") << QLatin1String("kurtosis_rayleigh")
                << QLatin1String("kurtosis_student_t") << QLatin1String("kurtosis_weibull") << QLatin1String("labels");

    m_functions << QLatin1String("lagrange") << QLatin1String("laguerre") << QLatin1String("lambda") << QLatin1String("laplace")
                << QLatin1String("laplacian_matrix") << QLatin1String("last") << QLatin1String("lbfgs")
                << QLatin1String("lc2kdt") << QLatin1String("lcharp") << QLatin1String("lc_l") << QLatin1String("lcm")
                << QLatin1String("lc_u") << QLatin1String("ldefint") << QLatin1String("ldisp") << QLatin1String("ldisplay")
                << QLatin1String("legendre_p") << QLatin1String("legendre_q") << QLatin1String("leinstein")
                << QLatin1String("length") << QLatin1String("let") << QLatin1String("letrules") << QLatin1String("letsimp")
                << QLatin1String("levi_civita") << QLatin1String("lfreeof") << QLatin1String("lgtreillis")
                << QLatin1String("lhs") << QLatin1String("li") << QLatin1String("liediff") << QLatin1String("limit")
                << QLatin1String("Lindstedt") << QLatin1String("linear") << QLatin1String("linearinterpol")
                << QLatin1String("linear_program") << QLatin1String("line_graph") << QLatin1String("linsolve")
                << QLatin1String("listarray") << QLatin1String("list_correlations") << QLatin1String("listify")
                << QLatin1String("list_nc_monomials") << QLatin1String("listoftens") << QLatin1String("listofvars")
                << QLatin1String("listp") << QLatin1String("lmax") << QLatin1String("lmin") << QLatin1String("load")
                << QLatin1String("loadfile") << QLatin1String("local") << QLatin1String("locate_matrix_entry")
                << QLatin1String("log") << QLatin1String("logand") << QLatin1String("logarc") << QLatin1String("logcontract")
                << QLatin1String("logor") << QLatin1String("logxor") << QLatin1String("lopow") << QLatin1String("lorentz_gauge")
                << QLatin1String("lowercasep") << QLatin1String("lpart") << QLatin1String("lratsubst")
                << QLatin1String("lreduce") << QLatin1String("lriemann") << QLatin1String("lsquares_estimates")
                << QLatin1String("lsquares_estimates_approximate") << QLatin1String("lsquares_estimates_exact")
                << QLatin1String("lsquares_mse") << QLatin1String("lsquares_residual_mse")
                << QLatin1String("lsquares_residuals") << QLatin1String("lsum") << QLatin1String("ltreillis")
                << QLatin1String("lu_backsub") << QLatin1String("lu_factor") << QLatin1String("macroexpand")
                << QLatin1String("macroexpand1") << QLatin1String("make_array") << QLatin1String("makebox")
                << QLatin1String("makefact") << QLatin1String("makegamma") << QLatin1String("make_level_picture")
                << QLatin1String("makelist") << QLatin1String("makeOrders") << QLatin1String("make_poly_continent")
                << QLatin1String("make_poly_country") << QLatin1String("make_polygon") << QLatin1String("make_random_state")
                << QLatin1String("make_rgb_picture") << QLatin1String("makeset") << QLatin1String("make_transform")
                << QLatin1String("mandelbrot") << QLatin1String("map") << QLatin1String("mapatom") << QLatin1String("maplist")
                << QLatin1String("matchdeclare") << QLatin1String("matchfix") << QLatin1String("mat_cond")
                << QLatin1String("mat_fullunblocker") << QLatin1String("mat_function") << QLatin1String("mat_norm")
                << QLatin1String("matrix") << QLatin1String("matrixmap") << QLatin1String("matrixp")
                << QLatin1String("matrix_size") << QLatin1String("mattrace") << QLatin1String("mat_trace")
                << QLatin1String("mat_unblocker") << QLatin1String("max") << QLatin1String("max_clique")
                << QLatin1String("max_degree") << QLatin1String("max_flow") << QLatin1String("maxi")
                << QLatin1String("maximize_lp") << QLatin1String("max_independent_set") << QLatin1String("max_matching")
                << QLatin1String("maybe") << QLatin1String("mean") << QLatin1String("mean_bernoulli")
                << QLatin1String("mean_beta") << QLatin1String("mean_binomial") << QLatin1String("mean_chi2")
                << QLatin1String("mean_continuous_uniform") << QLatin1String("mean_deviation")
                << QLatin1String("mean_discrete_uniform") << QLatin1String("mean_exp") << QLatin1String("mean_f")
                << QLatin1String("mean_gamma") << QLatin1String("mean_geometric") << QLatin1String("mean_gumbel")
                << QLatin1String("mean_hypergeometric") << QLatin1String("mean_laplace") << QLatin1String("mean_logistic")
                << QLatin1String("mean_lognormal") << QLatin1String("mean_negative_binomial") << QLatin1String("mean_normal")
                << QLatin1String("mean_pareto") << QLatin1String("mean_poisson") << QLatin1String("mean_rayleigh")
                << QLatin1String("mean_student_t") << QLatin1String("mean_weibull") << QLatin1String("median")
                << QLatin1String("median_deviation") << QLatin1String("member") << QLatin1String("metricexpandall")
                << QLatin1String("min") << QLatin1String("min_degree") << QLatin1String("minfactorial") << QLatin1String("mini")
                << QLatin1String("minimalPoly") << QLatin1String("minimize_lp") << QLatin1String("minimum_spanning_tree")
                << QLatin1String("minor") << QLatin1String("mnewton") << QLatin1String("mod") << QLatin1String("mode_declare")
                << QLatin1String("mode_identity") << QLatin1String("ModeMatrix") << QLatin1String("moebius")
                << QLatin1String("mon2schur") << QLatin1String("mono") << QLatin1String("monomial_dimensions")
                << QLatin1String("multi_elem") << QLatin1String("multinomial") << QLatin1String("multinomial_coeff")
                << QLatin1String("multi_orbit") << QLatin1String("multi_pui") << QLatin1String("multsym")
                << QLatin1String("multthru") << QLatin1String("mycielski_graph") << QLatin1String("nary")
                << QLatin1String("nc_degree") << QLatin1String("ncexpt") << QLatin1String("ncharpoly")
                << QLatin1String("negative_picture") << QLatin1String("neighbors") << QLatin1String("newcontext")
                << QLatin1String("newdet") << QLatin1String("new_graph") << QLatin1String("newline") << QLatin1String("newton")
                << QLatin1String("next_prime") << QLatin1String("niceindices") << QLatin1String("ninth")
                << QLatin1String("noncentral_moment") << QLatin1String("nonmetricity") << QLatin1String("nonnegintegerp")
                << QLatin1String("nonscalarp") << QLatin1String("nonzeroandfreeof") << QLatin1String("notequal")
                << QLatin1String("nounify") << QLatin1String("nptetrad") << QLatin1String("nroots") << QLatin1String("nterms")
                << QLatin1String("ntermst") << QLatin1String("nthroot") << QLatin1String("nullity")
                << QLatin1String("nullspace") << QLatin1String("num") << QLatin1String("numbered_boundaries")
                << QLatin1String("numberp") << QLatin1String("num_distinct_partitions") << QLatin1String("numerval")
                << QLatin1String("numfactor") << QLatin1String("num_partitions") << QLatin1String("nusum")
                << QLatin1String("odd_girth") << QLatin1String("oddp") << QLatin1String("ode2") << QLatin1String("ode_check")
                << QLatin1String("odelin") << QLatin1String("op") << QLatin1String("opena") << QLatin1String("openr")
                << QLatin1String("openw") << QLatin1String("operatorp") << QLatin1String("opsubst") << QLatin1String("optimize")
                << QLatin1String("orbit") << QLatin1String("orbits") << QLatin1String("ordergreat")
                << QLatin1String("ordergreatp") << QLatin1String("orderless") << QLatin1String("orderlessp")
                << QLatin1String("orthogonal_complement") << QLatin1String("orthopoly_recur")
                << QLatin1String("orthopoly_weight") << QLatin1String("outermap") << QLatin1String("out_neighbors")
                << QLatin1String("outofpois") << QLatin1String("pade") << QLatin1String("parGosper")
                << QLatin1String("parse_string") << QLatin1String("part") << QLatin1String("part2cont")
                << QLatin1String("partfrac") << QLatin1String("partition") << QLatin1String("partition_set")
                << QLatin1String("partpol") << QLatin1String("path_digraph") << QLatin1String("path_graph")
                << QLatin1String("pdf_bernoulli") << QLatin1String("pdf_beta") << QLatin1String("pdf_binomial")
                << QLatin1String("pdf_cauchy") << QLatin1String("pdf_chi2") << QLatin1String("pdf_continuous_uniform")
                << QLatin1String("pdf_discrete_uniform") << QLatin1String("pdf_exp") << QLatin1String("pdf_f")
                << QLatin1String("pdf_gamma") << QLatin1String("pdf_geometric") << QLatin1String("pdf_gumbel")
                << QLatin1String("pdf_hypergeometric") << QLatin1String("pdf_laplace") << QLatin1String("pdf_logistic")
                << QLatin1String("pdf_lognormal") << QLatin1String("pdf_negative_binomial") << QLatin1String("pdf_normal")
                << QLatin1String("pdf_pareto") << QLatin1String("pdf_poisson") << QLatin1String("pdf_rank_sum")
                << QLatin1String("pdf_rayleigh") << QLatin1String("pdf_signed_rank") << QLatin1String("pdf_student_t")
                << QLatin1String("pdf_weibull") << QLatin1String("pearson_skewness") << QLatin1String("permanent")
                << QLatin1String("permut") << QLatin1String("permutation") << QLatin1String("permutations")
                << QLatin1String("petersen_graph") << QLatin1String("petrov") << QLatin1String("pickapart")
                << QLatin1String("picture_equalp") << QLatin1String("picturep") << QLatin1String("piechart")
                << QLatin1String("planar_embedding") << QLatin1String("playback") << QLatin1String("plog")
                << QLatin1String("plot2d") << QLatin1String("plot3d") << QLatin1String("plotdf") << QLatin1String("plsquares")
                << QLatin1String("pochhammer") << QLatin1String("poisdiff") << QLatin1String("poisexpt")
                << QLatin1String("poisint") << QLatin1String("poismap") << QLatin1String("poisplus")
                << QLatin1String("poissimp") << QLatin1String("poissubst") << QLatin1String("poistimes")
                << QLatin1String("poistrim") << QLatin1String("polarform") << QLatin1String("polartorect")
                << QLatin1String("poly_add") << QLatin1String("poly_buchberger") << QLatin1String("poly_buchberger_criterion")
                << QLatin1String("poly_colon_ideal") << QLatin1String("poly_content") << QLatin1String("polydecomp")
                << QLatin1String("poly_depends_p") << QLatin1String("poly_elimination_ideal")
                << QLatin1String("poly_exact_divide") << QLatin1String("poly_expand") << QLatin1String("poly_expt")
                << QLatin1String("poly_gcd") << QLatin1String("poly_grobner") << QLatin1String("poly_grobner_equal")
                << QLatin1String("poly_grobner_member") << QLatin1String("poly_grobner_subsetp")
                << QLatin1String("poly_ideal_intersection") << QLatin1String("poly_ideal_polysaturation")
                << QLatin1String("poly_ideal_polysaturation1") << QLatin1String("poly_ideal_saturation");

    m_functions << QLatin1String("poly_ideal_saturation1") << QLatin1String("poly_lcm") << QLatin1String("poly_minimization")
                << QLatin1String("polymod") << QLatin1String("poly_multiply") << QLatin1String("polynome2ele")
                << QLatin1String("polynomialp") << QLatin1String("poly_normal_form") << QLatin1String("poly_normalize")
                << QLatin1String("poly_normalize_list") << QLatin1String("poly_polysaturation_extension")
                << QLatin1String("poly_primitive_part") << QLatin1String("poly_pseudo_divide")
                << QLatin1String("poly_reduced_grobner") << QLatin1String("poly_reduction")
                << QLatin1String("poly_saturation_extension") << QLatin1String("poly_s_polynomial")
                << QLatin1String("poly_subtract") << QLatin1String("polytocompanion") << QLatin1String("potential")
                << QLatin1String("power_mod") << QLatin1String("powers") << QLatin1String("powerseries")
                << QLatin1String("powerset") << QLatin1String("prev_prime") << QLatin1String("primep")
                << QLatin1String("print") << QLatin1String("printf") << QLatin1String("print_graph")
                << QLatin1String("printpois") << QLatin1String("printprops") << QLatin1String("prodrac")
                << QLatin1String("product") << QLatin1String("properties") << QLatin1String("propvars") << QLatin1String("psi")
                << QLatin1String("ptriangularize") << QLatin1String("pui") << QLatin1String("pui2comp")
                << QLatin1String("pui2ele") << QLatin1String("pui2polynome") << QLatin1String("pui_direct")
                << QLatin1String("puireduc") << QLatin1String("put") << QLatin1String("qput") << QLatin1String("qrange")
                << QLatin1String("quad_qag") << QLatin1String("quad_qagi") << QLatin1String("quad_qags")
                << QLatin1String("quad_qawc") << QLatin1String("quad_qawf") << QLatin1String("quad_qawo")
                << QLatin1String("quad_qaws") << QLatin1String("quantile") << QLatin1String("quantile_bernoulli")
                << QLatin1String("quantile_beta") << QLatin1String("quantile_binomial") << QLatin1String("quantile_cauchy")
                << QLatin1String("quantile_chi2") << QLatin1String("quantile_continuous_uniform")
                << QLatin1String("quantile_discrete_uniform") << QLatin1String("quantile_exp") << QLatin1String("quantile_f")
                << QLatin1String("quantile_gamma") << QLatin1String("quantile_geometric") << QLatin1String("quantile_gumbel")
                << QLatin1String("quantile_hypergeometric") << QLatin1String("quantile_laplace")
                << QLatin1String("quantile_logistic") << QLatin1String("quantile_lognormal")
                << QLatin1String("quantile_negative_binomial") << QLatin1String("quantile_normal")
                << QLatin1String("quantile_pareto") << QLatin1String("quantile_poisson") << QLatin1String("quantile_rayleigh")
                << QLatin1String("quantile_student_t") << QLatin1String("quantile_weibull")
                << QLatin1String("quartile_skewness") << QLatin1String("quit") << QLatin1String("qunit")
                << QLatin1String("quotient") << QLatin1String("radcan") << QLatin1String("radius") << QLatin1String("random")
                << QLatin1String("random_bernoulli") << QLatin1String("random_beta") << QLatin1String("random_binomial")
                << QLatin1String("random_cauchy") << QLatin1String("random_chi2") << QLatin1String("random_continuous_uniform")
                << QLatin1String("random_digraph") << QLatin1String("random_discrete_uniform") << QLatin1String("random_exp")
                << QLatin1String("random_f") << QLatin1String("random_gamma") << QLatin1String("random_geometric")
                << QLatin1String("random_graph") << QLatin1String("random_graph1") << QLatin1String("random_gumbel")
                << QLatin1String("random_hypergeometric") << QLatin1String("random_laplace") << QLatin1String("random_logistic")
                << QLatin1String("random_lognormal") << QLatin1String("random_negative_binomial")
                << QLatin1String("random_network") << QLatin1String("random_normal") << QLatin1String("random_pareto")
                << QLatin1String("random_permutation") << QLatin1String("random_poisson") << QLatin1String("random_rayleigh")
                << QLatin1String("random_regular_graph") << QLatin1String("random_student_t")
                << QLatin1String("random_tournament") << QLatin1String("random_tree") << QLatin1String("random_weibull")
                << QLatin1String("range") << QLatin1String("rank") << QLatin1String("rat") << QLatin1String("ratcoef")
                << QLatin1String("ratdenom") << QLatin1String("ratdiff") << QLatin1String("ratdisrep")
                << QLatin1String("ratexpand") << QLatin1String("rational") << QLatin1String("rationalize")
                << QLatin1String("ratnumer") << QLatin1String("ratnump") << QLatin1String("ratp") << QLatin1String("ratsimp")
                << QLatin1String("ratsubst") << QLatin1String("ratvars") << QLatin1String("ratweight") << QLatin1String("read")
                << QLatin1String("read_hashed_array") << QLatin1String("readline") << QLatin1String("read_lisp_array")
                << QLatin1String("read_list") << QLatin1String("read_matrix") << QLatin1String("read_maxima_array")
                << QLatin1String("read_nested_list") << QLatin1String("readonly") << QLatin1String("read_xpm")
                << QLatin1String("realpart") << QLatin1String("realroots") << QLatin1String("rearray")
                << QLatin1String("rectform") << QLatin1String("recttopolar") << QLatin1String("rediff")
                << QLatin1String("reduce_consts") << QLatin1String("reduce_order") << QLatin1String("region_boundaries")
                << QLatin1String("rem") << QLatin1String("remainder") << QLatin1String("remarray") << QLatin1String("rembox")
                << QLatin1String("remcomps") << QLatin1String("remcon") << QLatin1String("remcoord") << QLatin1String("remfun")
                << QLatin1String("remfunction") << QLatin1String("remlet") << QLatin1String("remove")
                << QLatin1String("remove_edge") << QLatin1String("remove_vertex") << QLatin1String("rempart")
                << QLatin1String("remrule") << QLatin1String("remsym") << QLatin1String("remvalue") << QLatin1String("rename")
                << QLatin1String("reset") << QLatin1String("residue") << QLatin1String("resolvante")
                << QLatin1String("resolvante_alternee1") << QLatin1String("resolvante_bipartite")
                << QLatin1String("resolvante_diedrale") << QLatin1String("resolvante_klein")
                << QLatin1String("resolvante_klein3") << QLatin1String("resolvante_produit_sym")
                << QLatin1String("resolvante_unitaire") << QLatin1String("resolvante_vierer") << QLatin1String("rest")
                << QLatin1String("resultant") << QLatin1String("return") << QLatin1String("reveal") << QLatin1String("reverse")
                << QLatin1String("revert") << QLatin1String("revert2") << QLatin1String("rgb2level") << QLatin1String("rhs")
                << QLatin1String("ricci") << QLatin1String("riemann") << QLatin1String("rinvariant") << QLatin1String("risch")
                << QLatin1String("rk") << QLatin1String("rncombine") << QLatin1String("romberg") << QLatin1String("room")
                << QLatin1String("rootscontract") << QLatin1String("row") << QLatin1String("rowop") << QLatin1String("rowswap")
                << QLatin1String("rreduce") << QLatin1String("run_testsuite") << QLatin1String("save")
                << QLatin1String("scalarp") << QLatin1String("scaled_bessel_i") << QLatin1String("scaled_bessel_i0")
                << QLatin1String("scaled_bessel_i1") << QLatin1String("scalefactors") << QLatin1String("scanmap")
                << QLatin1String("scatterplot") << QLatin1String("schur2comp") << QLatin1String("sconcat")
                << QLatin1String("scopy") << QLatin1String("scsimp") << QLatin1String("scurvature")
                << QLatin1String("sdowncase") << QLatin1String("sec") << QLatin1String("sech") << QLatin1String("second")
                << QLatin1String("sequal") << QLatin1String("sequalignore") << QLatin1String("setdifference")
                << QLatin1String("set_edge_weight") << QLatin1String("setelmx") << QLatin1String("setequalp")
                << QLatin1String("setify") << QLatin1String("setp") << QLatin1String("set_partitions")
                << QLatin1String("set_plot_option") << QLatin1String("set_random_state") << QLatin1String("setunits")
                << QLatin1String("setup_autoload") << QLatin1String("set_up_dot_simplifications")
                << QLatin1String("set_vertex_label") << QLatin1String("seventh") << QLatin1String("sexplode")
                << QLatin1String("sf") << QLatin1String("shortest_path") << QLatin1String("show") << QLatin1String("showcomps")
                << QLatin1String("showratvars") << QLatin1String("sign") << QLatin1String("signum")
                << QLatin1String("similaritytransform") << QLatin1String("simple_linear_regression")
                << QLatin1String("simplify_sum") << QLatin1String("simplode") << QLatin1String("simpmetderiv")
                << QLatin1String("simtran") << QLatin1String("sin") << QLatin1String("sinh") << QLatin1String("sinsert")
                << QLatin1String("sinvertcase") << QLatin1String("sixth") << QLatin1String("skewness")
                << QLatin1String("skewness_bernoulli") << QLatin1String("skewness_beta") << QLatin1String("skewness_binomial")
                << QLatin1String("skewness_chi2") << QLatin1String("skewness_continuous_uniform")
                << QLatin1String("skewness_discrete_uniform") << QLatin1String("skewness_exp") << QLatin1String("skewness_f")
                << QLatin1String("skewness_gamma") << QLatin1String("skewness_geometric") << QLatin1String("skewness_gumbel")
                << QLatin1String("skewness_hypergeometric") << QLatin1String("skewness_laplace")
                << QLatin1String("skewness_logistic") << QLatin1String("skewness_lognormal")
                << QLatin1String("skewness_negative_binomial") << QLatin1String("skewness_normal")
                << QLatin1String("skewness_pareto") << QLatin1String("skewness_poisson") << QLatin1String("skewness_rayleigh")
                << QLatin1String("skewness_student_t") << QLatin1String("skewness_weibull") << QLatin1String("slength")
                << QLatin1String("smake") << QLatin1String("smismatch") << QLatin1String("solve") << QLatin1String("solve_rec")
                << QLatin1String("solve_rec_rat") << QLatin1String("some") << QLatin1String("somrac") << QLatin1String("sort")
                << QLatin1String("sparse6_decode") << QLatin1String("sparse6_encode") << QLatin1String("sparse6_export")
                << QLatin1String("sparse6_import") << QLatin1String("specint") << QLatin1String("spherical_bessel_j")
                << QLatin1String("spherical_bessel_y") << QLatin1String("spherical_hankel1")
                << QLatin1String("spherical_hankel2") << QLatin1String("spherical_harmonic") << QLatin1String("splice")
                << QLatin1String("split") << QLatin1String("sposition") << QLatin1String("sprint") << QLatin1String("sqfr");

    m_functions << QLatin1String("sqrt") << QLatin1String("sqrtdenest") << QLatin1String("sremove")
                << QLatin1String("sremovefirst") << QLatin1String("sreverse") << QLatin1String("ssearch")
                << QLatin1String("ssort") << QLatin1String("sstatus") << QLatin1String("ssubst") << QLatin1String("ssubstfirst")
                << QLatin1String("staircase") << QLatin1String("status") << QLatin1String("std") << QLatin1String("std1")
                << QLatin1String("std_bernoulli") << QLatin1String("std_beta") << QLatin1String("std_binomial")
                << QLatin1String("std_chi2") << QLatin1String("std_continuous_uniform") << QLatin1String("std_discrete_uniform")
                << QLatin1String("std_exp") << QLatin1String("std_f") << QLatin1String("std_gamma")
                << QLatin1String("std_geometric") << QLatin1String("std_gumbel") << QLatin1String("std_hypergeometric")
                << QLatin1String("std_laplace") << QLatin1String("std_logistic") << QLatin1String("std_lognormal")
                << QLatin1String("std_negative_binomial") << QLatin1String("std_normal") << QLatin1String("std_pareto")
                << QLatin1String("std_poisson") << QLatin1String("std_rayleigh") << QLatin1String("std_student_t")
                << QLatin1String("std_weibull") << QLatin1String("stirling") << QLatin1String("stirling1")
                << QLatin1String("stirling2") << QLatin1String("strim") << QLatin1String("striml") << QLatin1String("strimr")
                << QLatin1String("string") << QLatin1String("stringout") << QLatin1String("stringp")
                << QLatin1String("strong_components") << QLatin1String("sublis") << QLatin1String("sublist")
                << QLatin1String("sublist_indices") << QLatin1String("submatrix") << QLatin1String("subsample")
                << QLatin1String("subset") << QLatin1String("subsetp") << QLatin1String("subst") << QLatin1String("substinpart")
                << QLatin1String("substpart") << QLatin1String("substring") << QLatin1String("subvar")
                << QLatin1String("subvarp") << QLatin1String("sum") << QLatin1String("sumcontract")
                << QLatin1String("summand_to_rec") << QLatin1String("supcase") << QLatin1String("supcontext")
                << QLatin1String("symbolp") << QLatin1String("symmdifference") << QLatin1String("symmetric")
                << QLatin1String("system") << QLatin1String("take_channel") << QLatin1String("take_inference")
                << QLatin1String("tan") << QLatin1String("tanh") << QLatin1String("taylor") << QLatin1String("taylorinfo")
                << QLatin1String("taylorp") << QLatin1String("taylor_simplifier") << QLatin1String("taytorat")
                << QLatin1String("tcl_output") << QLatin1String("tcontract") << QLatin1String("tellrat")
                << QLatin1String("tellsimp") << QLatin1String("tellsimpafter") << QLatin1String("tentex")
                << QLatin1String("tenth") << QLatin1String("test_mean") << QLatin1String("test_means_difference")
                << QLatin1String("test_normality") << QLatin1String("test_rank_sum") << QLatin1String("test_sign")
                << QLatin1String("test_signed_rank") << QLatin1String("test_variance") << QLatin1String("test_variance_ratio")
                << QLatin1String("tex") << QLatin1String("texput") << QLatin1String("%th") << QLatin1String("third")
                << QLatin1String("throw") << QLatin1String("time") << QLatin1String("timedate") << QLatin1String("timer")
                << QLatin1String("timer_info") << QLatin1String("tldefint") << QLatin1String("tlimit")
                << QLatin1String("todd_coxeter") << QLatin1String("toeplitz") << QLatin1String("tokens")
                << QLatin1String("to_lisp") << QLatin1String("topological_sort") << QLatin1String("totaldisrep")
                << QLatin1String("totalfourier") << QLatin1String("totient") << QLatin1String("tpartpol")
                << QLatin1String("trace") << QLatin1String("tracematrix") << QLatin1String("trace_options")
                << QLatin1String("translate") << QLatin1String("translate_file") << QLatin1String("transpose")
                << QLatin1String("tree_reduce") << QLatin1String("treillis") << QLatin1String("treinat")
                << QLatin1String("triangularize") << QLatin1String("trigexpand") << QLatin1String("trigrat")
                << QLatin1String("trigreduce") << QLatin1String("trigsimp") << QLatin1String("trunc")
                << QLatin1String("tr_warnings_get") << QLatin1String("ueivects") << QLatin1String("uforget")
                << QLatin1String("ultraspherical") << QLatin1String("underlying_graph") << QLatin1String("undiff")
                << QLatin1String("union") << QLatin1String("unique") << QLatin1String("uniteigenvectors")
                << QLatin1String("unit_step") << QLatin1String("unitvector") << QLatin1String("unknown")
                << QLatin1String("unorder") << QLatin1String("unsum") << QLatin1String("untellrat")
                << QLatin1String("untimer") << QLatin1String("untrace") << QLatin1String("uppercasep")
                << QLatin1String("uricci") << QLatin1String("uriemann") << QLatin1String("uvect")
                << QLatin1String("vandermonde_matrix") << QLatin1String("var") << QLatin1String("var1")
                << QLatin1String("var_bernoulli") << QLatin1String("var_beta") << QLatin1String("var_binomial")
                << QLatin1String("var_chi2") << QLatin1String("var_continuous_uniform") << QLatin1String("var_discrete_uniform")
                << QLatin1String("var_exp") << QLatin1String("var_f") << QLatin1String("var_gamma")
                << QLatin1String("var_geometric") << QLatin1String("var_gumbel") << QLatin1String("var_hypergeometric")
                << QLatin1String("var_laplace") << QLatin1String("var_logistic") << QLatin1String("var_lognormal")
                << QLatin1String("var_negative_binomial") << QLatin1String("var_normal") << QLatin1String("var_pareto")
                << QLatin1String("var_poisson") << QLatin1String("var_rayleigh") << QLatin1String("var_student_t")
                << QLatin1String("var_weibull") << QLatin1String("vectorpotential") << QLatin1String("vectorsimp")
                << QLatin1String("verbify") << QLatin1String("vers") << QLatin1String("vertex_coloring")
                << QLatin1String("vertex_degree") << QLatin1String("vertex_distance") << QLatin1String("vertex_eccentricity")
                << QLatin1String("vertex_in_degree") << QLatin1String("vertex_out_degree") << QLatin1String("vertices")
                << QLatin1String("vertices_to_cycle") << QLatin1String("vertices_to_path") << QLatin1String("weyl")
                << QLatin1String("wheel_graph") << QLatin1String("with_stdout") << QLatin1String("write_data")
                << QLatin1String("writefile") << QLatin1String("wronskian") << QLatin1String("xgraph_curves")
                << QLatin1String("xreduce") << QLatin1String("xthru") << QLatin1String("Zeilberger")
                << QLatin1String("zeroequiv") << QLatin1String("zerofor") << QLatin1String("zeromatrix")
                << QLatin1String("zeromatrixp") << QLatin1String("zeta") << QLatin1String("zlange");
    //Finish m_functions initialization

    // Begin m_keywords initialization
    m_keywords << QLatin1String("and") << QLatin1String("do") << QLatin1String("else") << QLatin1String("elseif")
               << QLatin1String("false") << QLatin1String("for") << QLatin1String("if") << QLatin1String("in")
               << QLatin1String("not") << QLatin1String("or") << QLatin1String("step") << QLatin1String("then")
               << QLatin1String("thru") << QLatin1String("true") << QLatin1String("while");
    //Finish m_keywords initialization
}

const QStringList& MaximaKeywords::variables() const
{
    return m_variables;
}

const QStringList& MaximaKeywords::functions() const
{
    return m_functions;
}

const QStringList& MaximaKeywords::keywords() const
{
    return m_keywords;
}
