#!/usr/bin/env bash

export SAGE_ROOT="$($1 --root)"

# Sage 9.2 stop source sage-env-config automatically, so do it manually
if [[ -f $SAGE_ROOT"/bin/sage-env" ]]; then
    if [[ -f $SAGE_ROOT"/bin/sage-env-config" ]]; then
        source "$SAGE_ROOT/bin/sage-env-config" >&2
    fi
    . "$SAGE_ROOT/bin/sage-env" >&2
elif [[ -f $SAGE_ROOT"/local/bin/sage-env" ]]; then
    if [[ -f $SAGE_ROOT"/local/bin/sage-env-config" ]]; then
        source "$SAGE_ROOT/local/bin/sage-env-config" >&2
    fi
    . "$SAGE_ROOT/local/bin/sage-env" >&2
elif [[ -f $SAGE_ROOT"/src/bin/sage-env" ]]; then
    if [[ -f $SAGE_ROOT"/src/bin/sage-env-config" ]]; then
        source "$SAGE_ROOT/src/bin/sage-env-config" >&2
    fi
    . "$SAGE_ROOT/src/bin/sage-env" >&2
fi

exec sage-ipython -i --simple-prompt
