#!/usr/bin/env bash

SAGE_ROOT="$($1 --root)"

if [[ -f $SAGE_ROOT"/bin/sage-env" ]]; then
    . "$SAGE_ROOT/bin/sage-env" >&2
elif [[ -f $SAGE_ROOT"/src/bin/sage-env" ]]; then
    . "$SAGE_ROOT/src/bin/sage-env" >&2
else
    exit 1 # We have a problem
fi

exec sage-ipython -i --simple-prompt