SET (LuaJIT_FOUND FALSE)
SET (LUAJIT_LIBRARY_NAME luajit-5.1)
SET (LUAJIT_INCLUDE_DIRS /usr/include/luajit-2.0 /usr/local/include/luajit-2.0)

FIND_PATH    (LUAJIT_INCLUDE_DIR lua.h ${LUAJIT_INCLUDE_DIRS} )
FIND_LIBRARY (LUAJIT_LIBRARY NAMES ${LUAJIT_LIBRARY_NAME} PATHS ${CMAKE_LIBRARY_PATH})

IF (LUAJIT_INCLUDE_DIR AND LUAJIT_LIBRARY)
    SET (LuaJIT_FOUND TRUE)
ENDIF (LUAJIT_INCLUDE_DIR AND LUAJIT_LIBRARY)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LuaJIT DEFAULT_MSG LUAJIT_LIBRARY LUAJIT_INCLUDE_DIR)
MARK_AS_ADVANCED ( LUAJIT_INCLUDE_DIR LUAJIT_LIBRARY)
